status = [
    # Travis CI
    "continuous-integration/travis-ci/push",
    # GitHub Actions
    "Build and test (ubuntu-latest, nightly)",
    "Build and test (windows-latest, nightly)",
    "Build and test (macOS-latest, nightly)",
    "Checking fmt and docs",
    "Clippy check",
]
