status = [
    # Travis CI
    "continuous-integration/travis-ci/push",
    # GitHub Actions
    "Build and test on ubuntu-latest",
    "Build and test on windows-latest",
    "Build and test on macOS-latest",
    "Checking fmt and docs",
    "Clippy check",
]
